### ISSUE TITLE
No Wave Animations For Copy To Clipboard

### ISSUE THREAD

**Issue by danielhickman** [WirelessBytes/materialcolorize#11]
Clicking in the right area is clicking on an SWF - therefore the button does not have material animation. The fix should be using the JS output of zero to trigger the animation

**Comment by danielhickman** [comment]
https://github.com/zeroclipboard/zeroclipboard/blob/master/docs/instructions.md#user-interaction-required

That means it is a limitation with zero that the ripple with never work, I'll be removing it until we use zero to trigger the animation
It completely covers the element with clip_button resulting in the CSS animation never being activated.

To address number 3:
Use this example to trigger the waves, make sure you add the waves-effect class along with the color being implemented.
```css
.clip_button.zeroclipboard-is-hover { background-color: #eee; }
.clip_button.zeroclipboard-is-active { background-color: #aaa; }
```
